sudo: false
dist: trusty
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - rust: stable
      env: "MINVER=true"
install:
  - rustup component add rustfmt-preview
script:
  - .travis/build.sh
